# -*- coding: utf-8 -*-
"""Waste_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BGCjO3QmBJDA38vCDfKCycPIFxSW0gXh
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("preetishah/waste-classificationorganic-and-recyclable")

print("Path to dataset files:", path)

train_path = "/kaggle/input/waste-classificationorganic-and-recyclable/wasteclassification/train"
test_path = "/kaggle/input/waste-classificationorganic-and-recyclable/wasteclassification/test"

from tensorflow.keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True,
                                   vertical_flip = True,
                                   rotation_range = 45,
                                   fill_mode = 'nearest')
test_datagen = ImageDataGenerator(rescale = 1./255)

train_generator = train_datagen.flow_from_directory(train_path,
                                                  target_size = (255, 255),
                                                  batch_size = 32,
                                                  class_mode = 'binary',
                                                  subset = 'training')

test_generator = test_datagen.flow_from_directory(test_path,
                                                  target_size = (255, 255),
                                                  batch_size = 32,
                                                  class_mode = 'binary')

#create CNN network
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
waste_cnn_model = Sequential()

#first layer
waste_cnn_model.add(Conv2D(32, (3,3), input_shape = (255, 255, 3), activation = 'relu'))
waste_cnn_model.add(MaxPooling2D(pool_size = (2,2)))
waste_cnn_model.add(Dropout(0.3))

#third layer
waste_cnn_model.add(Conv2D(64, (3,3), activation = 'relu'))
waste_cnn_model.add(Dropout(0.3))
waste_cnn_model.add(MaxPooling2D(2,2))
waste_cnn_model.add(Flatten())
waste_cnn_model.add(Dense(128, activation = 'relu'))
waste_cnn_model.add(Dropout(0.5))

#output
waste_cnn_model.add(Dense(1, activation = 'sigmoid'))

waste_cnn_model.summary()

#compile the moder
waste_cnn_model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

from tensorflow.keras.callbacks import EarlyStopping
early_stp = EarlyStopping(monitor = 'val_accuracy', patience = 3, restore_best_weights=True)
history = waste_cnn_model.fit(train_generator, epochs = 15, validation_data = test_generator, callbacks = [early_stp])

import matplotlib.pyplot as plt
plt.plot(history.history['loss'], label = "Training loss")
plt.plot(history.history['val_accuracy'], label = "Validation accuracy")
plt.legend()
plt.show()

#evaluate the model
waste_cnn_model.evaluate(test_generator)



waste_cnn_model.save("waste_classification.keras")

import tensorflow as tf
waste_model = tf.keras.models.load_model("waste_classification.keras")
#

#input the iamge
from tensorflow.keras.preprocessing import image
import numpy as np
image_path = "/content/10.jpeg"
my_image = image.load_img(image_path, target_size = (255, 255))
my_image_array = image.img_to_array(my_image)
my_image_array = np.expand_dims(my_image_array, axis = 0)
my_image_array = my_image_array/255.0

prediction = waste_model.predict(my_image_array)
print(prediction)

if prediction[0][0] > 0.5:
    print("Recyclable")
else:
    print("Organic")

from tensorflow.keras.preprocessing import image
if prediction[0][0] > 0.5:
    label = "Recyclable"
else:
    label = "Organic"

plt.imshow(image.load_img(image_path))
plt.title(f"Prediction is: {label}")
plt.show()

